import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TensorFlowProvider, useTensorFlow } from "@/providers/TensorFlowContext";
import { PoseDetectorProvider } from "@/providers/PoseDetectorContext";
import ClientProvidersWrapper from "@/providers/ClientProvidersWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PhysioTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TensorFlowProvider>
          <ClientProvidersWrapper>
            {children}
          </ClientProvidersWrapper> 
        </TensorFlowProvider>
      </body>
    </html>
  );
}
